version: "2.4"

services:
  snort:
    image: frapsoft/snort:latest
    container_name: snort
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./snort-lab/snort.conf:/etc/snort/snort.conf:ro
      - ./snort-lab/snort_defaults.conf:/etc/snort/snort_defaults.conf:ro
      - ./snort-lab/rules:/etc/snort/rules:ro
      - ./snort-lab/so_rules:/etc/snort/so_rules:ro
      - ./snort-lab/preproc_rules:/etc/snort/preproc_rules:ro
    command:
      - -c
      - /etc/snort/snort.conf
      - -i
      - eth0 # captura apenas a interface de rede do victim
      - -A
      - console
    depends_on:
      - victim
    network_mode: "service:victim"

  victim:
    image: nginx:latest
    container_name: victim

    networks:
      corp-net:
        ipv4_address: 192.168.10.20

  attacker:
    image: nicolaka/netshoot:latest
    container_name: attacker
    tty: true
    stdin_open: true

    networks:
      corp-net:
        ipv4_address: 192.168.20.50

networks:
  corp-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/16
